//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishopping.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ishopping.Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desculpem o transtorno, estamos em manutenção para melhor atendê-los. Retornaremos em breve e agradecemos a compreensão. Atenciosamente.
        /// </summary>
        public static string ManutencaoText {
            get {
                return ResourceManager.GetString("ManutencaoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Site em Manutenção.
        /// </summary>
        public static string ManutencaoTitle {
            get {
                return ResourceManager.GetString("ManutencaoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Troca de plano por um de maior valor.
        /// </summary>
        public static string Msg10000 {
            get {
                return ResourceManager.GetString("Msg10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O pagamento ainda não foi concluído.
        /// </summary>
        public static string Msg10001 {
            get {
                return ResourceManager.GetString("Msg10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguardando aprovação do pagamento.
        /// </summary>
        public static string Msg10002 {
            get {
                return ResourceManager.GetString("Msg10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento aprovado pela financeira.
        /// </summary>
        public static string Msg10003 {
            get {
                return ResourceManager.GetString("Msg10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento contestado pelo usuário.
        /// </summary>
        public static string Msg10004 {
            get {
                return ResourceManager.GetString("Msg10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento devolvido ao usuário.
        /// </summary>
        public static string Msg10005 {
            get {
                return ResourceManager.GetString("Msg10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transação cancelada sem ter sido finalizada.
        /// </summary>
        public static string Msg10006 {
            get {
                return ResourceManager.GetString("Msg10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento devolvido ao usuário.
        /// </summary>
        public static string Msg10007 {
            get {
                return ResourceManager.GetString("Msg10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Retido temporariamente.
        /// </summary>
        public static string Msg10008 {
            get {
                return ResourceManager.GetString("Msg10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento não aprovado.
        /// </summary>
        public static string Msg10009 {
            get {
                return ResourceManager.GetString("Msg10009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento deduzido do saldo atual do usuário.
        /// </summary>
        public static string Msg10010 {
            get {
                return ResourceManager.GetString("Msg10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status não definido.
        /// </summary>
        public static string Msg10011 {
            get {
                return ResourceManager.GetString("Msg10011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua senha foi alterada com sucesso..
        /// </summary>
        public static string PasswordSuccessfulyChanges {
            get {
                return ResourceManager.GetString("PasswordSuccessfulyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua nova senha é {0}.
        /// </summary>
        public static string ResetPasswordEmailBody {
            get {
                return ResourceManager.GetString("ResetPasswordEmailBody", resourceCulture);
            }
        }
    }
}
