//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishopping {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ishopping.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Botão.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a el el-question-sign.
        /// </summary>
        internal static string ElusiveIcons {
            get {
                return ResourceManager.GetString("ElusiveIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a fa-question-circle.
        /// </summary>
        internal static string FontAwesome {
            get {
                return ResourceManager.GetString("FontAwesome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a glyphicon glyphicon-question-sign.
        /// </summary>
        internal static string Glyphicons {
            get {
                return ResourceManager.GetString("Glyphicons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edite para alterar este item da lista .
        /// </summary>
        internal static string Lista {
            get {
                return ResourceManager.GetString("Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a . Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque euismod maximus erat at eleifend. Proin eget metus sed ex malesuada vulputate. Morbi lectus enim, tempus at turpis vel, molestie laoreet erat. Mauris eros urna, volutpat in euismod id, pharetra vel mauris. Vivamus nec luctus sapien.
        /// </summary>
        internal static string LoremLipsum_1 {
            get {
                return ResourceManager.GetString("LoremLipsum_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a . Maecenas quis ligula fringilla, posuere purus quis, ultricies ex. In tincidunt elit eleifend vehicula semper. Morbi tristique, arcu ut pharetra suscipit, ipsum dui venenatis nunc, vel tincidunt metus nisi vitae turpis. Praesent convallis turpis in leo lobortis commodo. Praesent eu nunc lacus. Fusce laoreet, mi id vestibulum pellentesque, lorem eros venenatis felis, id eleifend tortor nisl dapibus magna. In hac habitasse platea dictumst. Cum sociis natoque penatibus et magnis dis parturient montes, nascetu [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string LoremLipsum_2 {
            get {
                return ResourceManager.GetString("LoremLipsum_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desculpem o transtorno, estamos em manutenção para melhor atendê-los. Retornaremos em breve e agradecemos a compreensão. Atenciosamente.
        /// </summary>
        internal static string ManutencaoText {
            get {
                return ResourceManager.GetString("ManutencaoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Site em Manutenção.
        /// </summary>
        internal static string ManutencaoTitle {
            get {
                return ResourceManager.GetString("ManutencaoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a . Textos de tamanho pequeno podem conter até 32 caracteres, enquanto textos de tamanho médio podem conter até 512 carecteres e textos de tamanho grande podem conter até 5128 caracteres.
        /// </summary>
        internal static string TextoAdicional {
            get {
                return ResourceManager.GetString("TextoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este é um texto de tamanho grande que ocupa a posição .
        /// </summary>
        internal static string TextoGrande {
            get {
                return ResourceManager.GetString("TextoGrande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este é um texto de tamanho médio que ocupa a posição .
        /// </summary>
        internal static string TextoMedio {
            get {
                return ResourceManager.GetString("TextoMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Texto pequeno.
        /// </summary>
        internal static string TextoPequeno {
            get {
                return ResourceManager.GetString("TextoPequeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://www.youtube.com/embed/OKrI1eKABgM.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
